wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711348722.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.9.13
      5: 0.16.4
      6: 4.30.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
